name: Sync Google Sheet CSV

on:
  schedule:
    # Runs every 1 hour (你可以根据需要调整频率)
    # Cron 语法：MINUTE HOUR DAY_OF_MONTH MONTH DAY_OF_WEEK
    # 例如：
    # '0 * * * *'  - 每小时的0分
    # '0 0 * * *'  - 每天午夜
    # '0 0 * * 1'  - 每周一午夜
    - cron: '0 * * * *'
  workflow_dispatch:
    # 允许手动触发此工作流

jobs:
  sync_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # 使用v4版本

    - name: Fetch Google Sheet CSV
      id: fetch_csv
      run: |
        GOOGLE_SHEET_CSV_URL="${{ vars.GOOGLE_SHEET_CSV_URL || 'https://docs.google.com/spreadsheets/d/e/2PAC-1vQJ__EJVsqIpDJbdyKPh8nwpyd0GUdwm-Ivdl4rsD_-k9oruRccECXHwigtJOrOaIt8LtcNwEP3OxUY/pub?gid=0&single=true&output=csv' }}"
        
        # 定义保存CSV的文件路径
        CSV_FILE_PATH="data/your_data.csv" # 你可以自定义这个路径和文件名
        
        mkdir -p data # 确保目录存在
        
        curl -L "$GOOGLE_SHEET_CSV_URL" -o "$CSV_FILE_PATH"

        # 检查是否成功下载
        if [ ! -f "$CSV_FILE_PATH" ]; then
          echo "Error: CSV file was not downloaded."
          exit 1
        fi
        echo "CSV downloaded to $CSV_FILE_PATH"
        
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push if changes exist
      run: |
        git add .
        # 检查是否有实际的更改，避免空提交
        if ! git diff-index --quiet HEAD; then
          git commit -m "Update data from Google Sheet [skip ci]"
          git push
        else
          echo "No changes in CSV file. Skipping commit."
        fi
      env:
        # 使用你之前设置的秘钥来认证
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # 确保这里的名称与你设置的秘钥名称一致
